server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://kasandrachumpitaz:3Q3aLVYPP3T0uhia@cluster0.qazj0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0